Repository MaterialiseAgency/pardot, pull requests merged in 2022-08, with the labels that each got.

#62 contact template
  public/pages/contact-template-test.html
  public/pages/сontact-template-local.html
Labels: review

#71 update script location
  public/pages/event-template-local.html
  public/pages/event-template-production.html
  public/pages/event-template-test.html
  public/pages/event-template-uat.html
  public/pages/form-event-template-local.html
  public/pages/form-event-template-production.html
  public/pages/form-event-template-test.html
  public/pages/form-event-template-uat.html
Labels: test

#77 76 pardot 41757 add script redirects
  public/pages/events.js
  public/pages/seo_before_gtm.js
Labels: test

#78 Script setup
  public/pages/events.js
Labels: test

#79 Script setup
  public/pages/events.js
  public/pages/form-event-template-local.html
  public/pages/form-event-template-production.html
  public/pages/form-event-template-test.html
Labels: test

#80 76 pardot 41757 add script redirects
  public/pages/events.js
  public/pages/form-event-template-local.html
  public/pages/form-event-template-production.html
  public/pages/form-event-template-test.html
  public/pages/seo_before_gtm.js
Labels: review

#81 UAT
  public/pages/events.js
  public/pages/form-event-template-local.html
  public/pages/form-event-template-production.html
  public/pages/form-event-template-test.html
  public/pages/seo_before_gtm.js
Labels: release

#82 Production
  public/pages/events.js
  public/pages/form-event-template-local.html
  public/pages/form-event-template-production.html
  public/pages/form-event-template-test.html
  public/pages/seo_before_gtm.js
Labels: release

#85 84 pardot 41757 fix event template
  public/pages/event-template-production.html
  public/pages/event-template-test.html
Labels: review

#86 Fix
  public/pages/event-template-local.html
  public/pages/event-template-production.html
  public/pages/event-template-uat.html
Labels: test

#87 84 pardot 41757 fix event template
  public/pages/event-template-local.html
  public/pages/event-template-production.html
  public/pages/event-template-test.html
  public/pages/event-template-uat.html
Labels: review

#89 UAT
  public/pages/event-template-local.html
  public/pages/event-template-production.html
  public/pages/event-template-test.html
  public/pages/event-template-uat.html
Labels: release

#90 Production
  public/pages/event-template-local.html
  public/pages/event-template-production.html
  public/pages/event-template-test.html
  public/pages/event-template-uat.html
Labels: release

#88 get url script
  public/pages/events.js
Labels: review

#91 Test
  public/pages/events.js
Labels: test

#92 UAT
  public/pages/events.js
Labels: release

#93 Production
  public/pages/events.js
Labels: release

#96 95 pardot 0001 general updates
  package-lock.json
  public/pages/event-template-local.html
  public/pages/event-template-production.html
  public/pages/event-template-test.html
  public/pages/event-template-uat.html
  public/pages/seo_before_gtm.js
Labels: test

#97 Remove redirect script
  public/pages/events.js
Labels: test

#98 95 pardot 0001 general updates
  package-lock.json
  public/pages/event-template-local.html
  public/pages/event-template-production.html
  public/pages/event-template-test.html
  public/pages/event-template-uat.html
  public/pages/events.js
  public/pages/seo_before_gtm.js
Labels: review

#99 UAT
  package-lock.json
  public/pages/event-template-local.html
  public/pages/event-template-production.html
  public/pages/event-template-test.html
  public/pages/event-template-uat.html
  public/pages/events.js
  public/pages/seo_before_gtm.js
Labels: release

#100 Production
  package-lock.json
  public/pages/event-template-local.html
  public/pages/event-template-production.html
  public/pages/event-template-test.html
  public/pages/event-template-uat.html
  public/pages/events.js
  public/pages/seo_before_gtm.js
Labels: release

#101 JS error on Windo location
  public/pages/seo_before_gtm.js
Labels: bug

#102 UAT
  public/pages/seo_before_gtm.js
Labels: release

#103 Production
  public/pages/seo_before_gtm.js
Labels: release

#104 Test
  public/pages/seo_before_gtm.js
Labels: test

#106 Production
  public/pages/seo_before_gtm.js
Labels: release

#107 UAT
  public/pages/seo_before_gtm.js
Labels: release

#109 event template 1.1
  public/pages/event-template-local.html
  public/pages/event-template-production.html
  public/pages/event-template-test.html
  public/pages/event-template-uat.html
  public/pages/form-event-template-local.html
  public/pages/form-event-template-uat.html
Labels: review

#110 Production
  public/pages/event-template-local.html
  public/pages/event-template-production.html
  public/pages/event-template-test.html
  public/pages/event-template-uat.html
  public/pages/form-event-template-local.html
  public/pages/form-event-template-uat.html
Labels: release

#111 95 pardot 0001 general updates
  public/pages/event-template-production.html
  public/pages/seo_before_gtm.js
  src/style.css
Labels: review

#112 Production
  public/pages/event-template-production.html
  public/pages/seo_before_gtm.js
  src/style.css
Labels: release

#114 Production
  public/assets/favicon-16x16.png
  public/assets/favicon-32x32.png
  public/pages/event-template-production.html
  public/pages/event-template-test.html
Labels: release

#115 95 pardot 0001 general updates
  public/pages/seo_before_gtm.js
Labels: review

#116 Production
  public/pages/seo_before_gtm.js
Labels: release

#117 SEO form submit
  public/pages/seo_after_gtm.js
Labels: review

#118 Production
  public/pages/seo_after_gtm.js
  public/pages/seo_before_gtm.js
Labels: release

#122 Production
  public/pages/event-template-test.html
  public/pages/form-event-template-production.html
  public/pages/form-event-template-test.html
Labels: release

#123 Fix on links
  public/pages/event-template-test.html
  public/pages/form-event-template-test.html
Labels: review

#129 Release
  public/pages/seo_after_gtm.js
Labels: release

#130 SEO Updates
  public/pages/event-template-local.html
  public/pages/event-template-production.html
  public/pages/event-template-test.html
Labels: review

#131 Release
  public/pages/event-template-local.html
  public/pages/event-template-production.html
  public/pages/event-template-test.html
Labels: release

#132 SEO Updates
  public/pages/seo_after_gtm.js
Labels: review

#133 Release
  public/pages/seo_after_gtm.js
Labels: release

#134 Update seo script
  public/pages/seo_after_gtm.js
Labels: review

#135 Release
  public/pages/seo_after_gtm.js
Labels: release

#136 Update OG
  public/pages/event-template-production.html
Labels: review

#137 Production
  public/pages/event-template-production.html
Labels: release

#142 Event Template update
  public/pages/event-template-local.html
  public/pages/event-template-production.html
  public/pages/event-template-test.html
  public/pages/seo_before_gtm.js
Labels: review

#143 Release
  public/pages/event-template-local.html
  public/pages/event-template-production.html
  public/pages/event-template-test.html
  public/pages/seo_before_gtm.js
Labels: release

#144 Fix styles for button
  public/pages/event-template-local.html
  public/pages/event-template-production.html
  public/pages/event-template-test.html
Labels: review

#145 Production
  public/pages/event-template-local.html
  public/pages/event-template-production.html
  public/pages/event-template-test.html
Labels: release

#156 Payment page
  public/pages/payment-page.html
Labels: review

#157 Release
  public/pages/payment-page.html
Labels: release

#159 Event form template updates
  public/pages/CMF_EACMFS.html
  public/pages/event-template-production.html
  public/pages/form-event-template-production.html
Labels: review

#162 Production
  public/pages/CMF_EACMFS.html
  public/pages/event-template-production.html
  public/pages/form-event-template-production.html
Labels: release
